ansys/aedt-testing

- README.md
Added how to access CLI Help in the Documentation
> How to access CLI Help

- aedttest/aedt_test_runner.py
- aedttest/simulation_data.py
> move class init into exception handler

- tests/input/prof_test_mixed_case.prof
> modified prof file

- .github/workflows/ci.yml
- aedttest/aedt_test_runner.py
- docs/CONTRIBUTE.md
end to end tested on Slurm cluster with drive shared across compute nodes
> save simulation data in CWD by default

- aedttest/simulation_data.py
- pyproject.toml
Bug fixed, frequency sweep must not be considered to retrieve mesh and profile. Only LastAdaptive.
> Retrieve profile and mesh info only from LastAdaptive

- .gitignore
- README.md
- aedttest/aedt_test_runner.py
- tests/input/reference_simple/ref_sample.json
- tests/unittests/test_aedt_test_runner.py
store each reference result separately and request user to provide a path to a reference folder
> Ref folder

- aedttest/aedt_test_runner.py
- examples/configs/config_with_comments.toml
- tests/unittests/test_aedt_test_runner.py
> Config rework

- aedttest/simulation_data.py
> add argument for logging level

- aedttest/aedt_test_runner.py
- tests/unittests/test_aedt_test_runner.py
> do not split tasks on auto false

- aedttest/aedt_test_runner.py
> pass debug info to solver

- .github/workflows/ci-sim-data.yml
- .github/workflows/ci.yml
- .github/workflows/pre-commit.yml
disable CI on master, since we block pushes to master
> disable CI on master

- .pre-commit-config.yaml
- aedttest/static/css/style.css
- aedttest/static/js/chartjs-init.js
- aedttest/static/js/common.js
- aedttest/static/js/main.js
- aedttest/static/js/project.js
- aedttest/static/templates/main.html
- aedttest/static/templates/project-report.html
> added autostyle

- aedttest/simulation_data.py
> insert pyadet path at top

- aedttest/aedt_test_runner.py
- Avoid duplicated file names
-  Relative path
> Relative path in HTML file

- aedttest/aedt_test_runner.py
> Add profile folder per project

- aedttest/simulation_data.py
- pyproject.toml
bump pyaedt
remove access to protected member
fix docstrings
> fix pycharm warnings

- pyproject.toml
> bump pyaedt

- aedttest/aedt_test_runner.py
- tests/unittests/test_web_pages.py
> sort projects by name on main.html

- aedttest/aedt_test_runner.py
- aedttest/simulation_data.py
- docs/CONTRIBUTE.md
Closes #198
Closes #210 
Closes #213
> Fix pyaedt error messages

- aedttest/aedt_test_runner.py
> Fix Reference results file bug

- .pre-commit-config.yaml
- pyproject.toml
> pyadet bump 0.6.25 fix pytonnet issue
